
package mm.rest;


public class ConfigClientFormatOldReps {

    public String aboutLink;
    public String administratorsGuideLink;
    public String allowEditPost;
    public String androidAppDownloadLink;
    public String appDownloadLink;
    public String availableLocales;
    public String buildDate;
    public String buildEnterpriseReady;
    public String buildHash;
    public String buildHashEnterprise;
    public String buildNumber;
    public String commercialSupportLink;
    public String defaultClientLocale;
    public String diagnosticId;
    public String diagnosticsEnabled;
    public String enableCommands;
    public String enableCustomEmoji;
    public String enableDeveloper;
    public String enableDiagnostics;
    public String enableEmailBatching;
    public String enableFileAttachments;
    public String enableIncomingWebhooks;
    public String enableLinkPreviews;
    public String enableOAuthServiceProvider;
    public String enableOnlyAdminIntegrations;
    public String enableOpenServer;
    public String enableOutgoingWebhooks;
    public String enablePostIconOverride;
    public String enablePostUsernameOverride;
    public String enablePublicLink;
    public String enableSignInWithEmail;
    public String enableSignInWithUsername;
    public String enableSignUpWithEmail;
    public String enableSignUpWithGitLab;
    public String enableTeamCreation;
    public String enableTesting;
    public String enableUserCreation;
    public String enableUserTypingMessages;
    public String enableWebrtc;
    public String googleDeveloperKey;
    public String helpLink;
    public String iosAppDownloadLink;
    public String maxFileSize;
    public String maxNotificationsPerChannel;
    public String noAccounts;
    public String postEditTimeLimit;
    public String privacyPolicyLink;
    public String profileHeight;
    public String profileWidth;
    public String reportAProblemLink;
    public String requireEmailVerification;
    public String restrictCustomEmojiCreation;
    public String restrictDirectMessage;
    public String restrictPostDelete;
    public String restrictPrivateChannelCreation;
    public String restrictPrivateChannelDeletion;
    public String restrictPrivateChannelManageMembers;
    public String restrictPrivateChannelManagement;
    public String restrictPublicChannelCreation;
    public String restrictPublicChannelDeletion;
    public String restrictPublicChannelManagement;
    public String restrictTeamInvite;
    public String sQLDriverName;
    public String sendEmailNotifications;
    public String sendPushNotifications;
    public String showEmailAddress;
    public String siteName;
    public String siteURL;
    public String supportEmail;
    public String termsOfServiceLink;
    public String timeBetweenUserTypingUpdatesMilliseconds;
    public String troubleshootingForumLink;
    public String version;
    public String websocketPort;
    public String websocketSecurePort;

}
